name: Auto Assign
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
jobs:
  call:
    uses: control-toolbox/CTActions/.github/workflows/auto-assign.yml@main
    with:
      assignees: AnasXbouali
      numOfAssignee: 1